export const SAFE_UNIVERSE = new Set([
  'BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT',
  'DOGEUSDT','ADAUSDT','AVAXUSDT','DOTUSDT','MATICUSDT',
  'LINKUSDT','LTCUSDT','UNIUSDT','ATOMUSDT','NEARUSDT',
  'APTUSDT','ARBUSDT','OPUSDT','INJUSDT','SUIUSDT',
  'SEIUSDT','TIAUSDT','WIFUSDT','PEPEUSDT','FLOKIUSDT',
  'BONKUSDT','FETUSDT','RENDERUSDT','WLDUSDT','JUPUSDT',
  'ENAUSDT','NEIROUSDT','KAIAUSDT','TAOUSDT','STRKUSDT',
  'EIGENUSDT','MOVEUSDT','MEUSDT','PNUTUSDT','TURBOUSDT',
]);

export const FALLBACK_TRADING_PAIRS = [
  'BTCUSDT', 'ETHUSDT', 'SOLUSDT'
];

export const MIN_CONFIDENCE_FULL = 60;
export const MIN_CONFIDENCE_HALF = 55;
export const MIN_RR_RATIO = 2.0;
export const TARGET_RR_RATIO = 2.5;
